name: aioCloud CI
on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        shell: bash
        run: |
          go test ./...
